apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume
  labels:
    type: local
spec: 
  storageClassName: manual # or slow
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/home/jmirre/skores/POC-WINCOMP/registry"

