kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
  labels:
    type: local
  namespace: localdeploy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
